#!/usr/bin/env python3
"""Convert the MAME 'digdug' ROM set into a C header for STRATUM.

usage: convert_roms.py <romdir> [outdir]   (default outdir: ../main/roms)
"""
import sys, zlib
from pathlib import Path

CPU1 = [('dd1a.1', 0x1000), ('dd1a.2', 0x1000), ('dd1a.3', 0x1000), ('dd1a.4', 0x1000)]
CPU2 = [('dd1a.5', 0x1000), ('dd1a.6', 0x1000)]
CPU3 = [('dd1.7',  0x1000)]
CHR  = [('dd1.9',  0x0800)]                      # 1bpp text characters
SPR  = [('dd1.15', 0x1000), ('dd1.14', 0x1000), ('dd1.13', 0x1000), ('dd1.12', 0x1000)]
BGT  = [('dd1.11', 0x1000)]                      # 2bpp background tiles
PLAY = [('dd1.10b', 0x1000)]                     # the playfield map: which tile goes where
PROM_PAL  = ('136007.113', 0x20)                 # 32 colours
PROM_SPR  = ('136007.111', 0x100)                # sprite colour lookup
PROM_BG   = ('136007.112', 0x100)                # background colour lookup
PROM_WAVE = ('136007.110', 0x100)                # 8 WSG waveforms of 32 samples

def load(romdir, name, size):
    p = romdir / name
    if not p.exists():
        sys.exit(f'{name}: not found in {romdir}')
    data = p.read_bytes()
    if len(data) != size:
        sys.exit(f'{name}: {len(data)} bytes, expected {size}')
    print(f'  {name}: {len(data)} bytes, crc32 {zlib.crc32(data) & 0xffffffff:08x}')
    return data

def cat(romdir, items):
    return b''.join(load(romdir, n, s) for n, s in items)

def c_array(name, data, dims):
    lines = [f'static const uint8_t {name}{dims} = {{']
    for i in range(0, len(data), 24):
        lines.append('    ' + ','.join(f'0x{b:02X}' for b in data[i:i+24]) + ',')
    lines.append('};')
    return '\n'.join(lines)

def main():
    romdir = Path(sys.argv[1] if len(sys.argv) > 1 else 'digdug')
    outdir = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).resolve().parent.parent / 'main' / 'roms'
    outdir.mkdir(parents=True, exist_ok=True)
    print(f'ROMs: {romdir}')
    out = ['/* digdug_roms.h - AUTO-GENERATED by tools/convert_roms.py - DO NOT COMMIT */',
           '#ifndef DIGDUG_ROMS_H', '#define DIGDUG_ROMS_H', '#include <stdint.h>', '',
           c_array('dd_cpu1', cat(romdir, CPU1), '[0x4000]'), '',
           c_array('dd_cpu2', cat(romdir, CPU2), '[0x2000]'), '',
           c_array('dd_cpu3', cat(romdir, CPU3), '[0x1000]'), '',
           c_array('dd_chr',  cat(romdir, CHR),  '[0x800]'), '',
           c_array('dd_spr',  cat(romdir, SPR),  '[0x4000]'), '',
           c_array('dd_bgt',  cat(romdir, BGT),  '[0x1000]'), '',
           c_array('dd_play', cat(romdir, PLAY), '[0x1000]'), '',
           c_array('dd_pal',  load(romdir, *PROM_PAL),  '[0x20]'), '',
           c_array('dd_lut_spr', load(romdir, *PROM_SPR), '[0x100]'), '',
           c_array('dd_lut_bg',  load(romdir, *PROM_BG),  '[0x100]'), '',
           c_array('dd_wave', load(romdir, *PROM_WAVE), '[0x100]'), '',
           '#endif']
    (outdir / 'digdug_roms.h').write_text('\n'.join(out))
    print(f'wrote {outdir / "digdug_roms.h"}')

if __name__ == '__main__':
    main()
